// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.4.0
// source: dao.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet  *NetPacket  `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Request *NetRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Content string      `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *BroadcastReq) Reset() {
	*x = BroadcastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReq) ProtoMessage() {}

func (x *BroadcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReq.ProtoReflect.Descriptor instead.
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastReq) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *BroadcastReq) GetRequest() *NetRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *BroadcastReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type BroadcastRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet   *NetPacket   `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Response *NetResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *BroadcastRsp) Reset() {
	*x = BroadcastRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRsp) ProtoMessage() {}

func (x *BroadcastRsp) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRsp.ProtoReflect.Descriptor instead.
func (*BroadcastRsp) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastRsp) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *BroadcastRsp) GetResponse() *NetResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type QueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet  *NetPacket  `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Request *NetRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *QueryReq) Reset() {
	*x = QueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReq) ProtoMessage() {}

func (x *QueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReq.ProtoReflect.Descriptor instead.
func (*QueryReq) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{2}
}

func (x *QueryReq) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *QueryReq) GetRequest() *NetRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type QueryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet   *NetPacket   `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Response *NetResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Users    []string     `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *QueryRsp) Reset() {
	*x = QueryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRsp) ProtoMessage() {}

func (x *QueryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRsp.ProtoReflect.Descriptor instead.
func (*QueryRsp) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRsp) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *QueryRsp) GetResponse() *NetResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *QueryRsp) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type RenameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet  *NetPacket  `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Request *NetRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	NewName string      `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *RenameReq) Reset() {
	*x = RenameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameReq) ProtoMessage() {}

func (x *RenameReq) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameReq.ProtoReflect.Descriptor instead.
func (*RenameReq) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{4}
}

func (x *RenameReq) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *RenameReq) GetRequest() *NetRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RenameReq) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet   *NetPacket   `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Response *NetResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	NewName  string       `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *RenameRsp) Reset() {
	*x = RenameRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRsp) ProtoMessage() {}

func (x *RenameRsp) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRsp.ProtoReflect.Descriptor instead.
func (*RenameRsp) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{5}
}

func (x *RenameRsp) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *RenameRsp) GetResponse() *NetResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RenameRsp) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type PrivateChatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet  *NetPacket  `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Request *NetRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	User    string      `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Content string      `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PrivateChatReq) Reset() {
	*x = PrivateChatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateChatReq) ProtoMessage() {}

func (x *PrivateChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateChatReq.ProtoReflect.Descriptor instead.
func (*PrivateChatReq) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{6}
}

func (x *PrivateChatReq) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *PrivateChatReq) GetRequest() *NetRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PrivateChatReq) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PrivateChatReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PrivateChatRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet   *NetPacket   `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Response *NetResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PrivateChatRsp) Reset() {
	*x = PrivateChatRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateChatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateChatRsp) ProtoMessage() {}

func (x *PrivateChatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateChatRsp.ProtoReflect.Descriptor instead.
func (*PrivateChatRsp) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{7}
}

func (x *PrivateChatRsp) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *PrivateChatRsp) GetResponse() *NetResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type KickPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet *NetPacket `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Push   *NetPush   `protobuf:"bytes,2,opt,name=push,proto3" json:"push,omitempty"`
}

func (x *KickPush) Reset() {
	*x = KickPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPush) ProtoMessage() {}

func (x *KickPush) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPush.ProtoReflect.Descriptor instead.
func (*KickPush) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{8}
}

func (x *KickPush) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *KickPush) GetPush() *NetPush {
	if x != nil {
		return x.Push
	}
	return nil
}

type BroadcastPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet  *NetPacket `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Push    *NetPush   `protobuf:"bytes,2,opt,name=push,proto3" json:"push,omitempty"`
	User    string     `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Content string     `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *BroadcastPush) Reset() {
	*x = BroadcastPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastPush) ProtoMessage() {}

func (x *BroadcastPush) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastPush.ProtoReflect.Descriptor instead.
func (*BroadcastPush) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{9}
}

func (x *BroadcastPush) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *BroadcastPush) GetPush() *NetPush {
	if x != nil {
		return x.Push
	}
	return nil
}

func (x *BroadcastPush) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BroadcastPush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PrivateChatPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet  *NetPacket `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Push    *NetPush   `protobuf:"bytes,2,opt,name=push,proto3" json:"push,omitempty"`
	User    string     `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Content string     `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PrivateChatPush) Reset() {
	*x = PrivateChatPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dao_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateChatPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateChatPush) ProtoMessage() {}

func (x *PrivateChatPush) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateChatPush.ProtoReflect.Descriptor instead.
func (*PrivateChatPush) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{10}
}

func (x *PrivateChatPush) GetPacket() *NetPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *PrivateChatPush) GetPush() *NetPush {
	if x != nil {
		return x.Push
	}
	return nil
}

func (x *PrivateChatPush) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PrivateChatPush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_dao_proto protoreflect.FileDescriptor

var file_dao_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x10, 0x6e, 0x65, 0x74, 0x2d, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x79, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4e,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x62, 0x0a, 0x0c,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x5b, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x06,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x74, 0x0a,
	0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4e,
	0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x22, 0x77, 0x0a, 0x09, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x25, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7a, 0x0a, 0x09,
	0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4e,
	0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x06, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x4e, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x64, 0x0a, 0x0e, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x52, 0x0a, 0x08, 0x4b, 0x69, 0x63, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x12, 0x25, 0x0a, 0x06,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x75, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x04,
	0x70, 0x75, 0x73, 0x68, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1f, 0x0a,
	0x04, 0x70, 0x75, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x4e, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x04, 0x70, 0x75, 0x73, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x87, 0x01, 0x0a,
	0x0f, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x50, 0x75, 0x73, 0x68,
	0x12, 0x25, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x75, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x75,
	0x73, 0x68, 0x52, 0x04, 0x70, 0x75, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6d, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dao_proto_rawDescOnce sync.Once
	file_dao_proto_rawDescData = file_dao_proto_rawDesc
)

func file_dao_proto_rawDescGZIP() []byte {
	file_dao_proto_rawDescOnce.Do(func() {
		file_dao_proto_rawDescData = protoimpl.X.CompressGZIP(file_dao_proto_rawDescData)
	})
	return file_dao_proto_rawDescData
}

var file_dao_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dao_proto_goTypes = []interface{}{
	(*BroadcastReq)(nil),    // 0: pb.BroadcastReq
	(*BroadcastRsp)(nil),    // 1: pb.BroadcastRsp
	(*QueryReq)(nil),        // 2: pb.QueryReq
	(*QueryRsp)(nil),        // 3: pb.QueryRsp
	(*RenameReq)(nil),       // 4: pb.RenameReq
	(*RenameRsp)(nil),       // 5: pb.RenameRsp
	(*PrivateChatReq)(nil),  // 6: pb.PrivateChatReq
	(*PrivateChatRsp)(nil),  // 7: pb.PrivateChatRsp
	(*KickPush)(nil),        // 8: pb.KickPush
	(*BroadcastPush)(nil),   // 9: pb.BroadcastPush
	(*PrivateChatPush)(nil), // 10: pb.PrivateChatPush
	(*NetPacket)(nil),       // 11: pb.NetPacket
	(*NetRequest)(nil),      // 12: pb.NetRequest
	(*NetResponse)(nil),     // 13: pb.NetResponse
	(*NetPush)(nil),         // 14: pb.NetPush
}
var file_dao_proto_depIdxs = []int32{
	11, // 0: pb.BroadcastReq.packet:type_name -> pb.NetPacket
	12, // 1: pb.BroadcastReq.request:type_name -> pb.NetRequest
	11, // 2: pb.BroadcastRsp.packet:type_name -> pb.NetPacket
	13, // 3: pb.BroadcastRsp.response:type_name -> pb.NetResponse
	11, // 4: pb.QueryReq.packet:type_name -> pb.NetPacket
	12, // 5: pb.QueryReq.request:type_name -> pb.NetRequest
	11, // 6: pb.QueryRsp.packet:type_name -> pb.NetPacket
	13, // 7: pb.QueryRsp.response:type_name -> pb.NetResponse
	11, // 8: pb.RenameReq.packet:type_name -> pb.NetPacket
	12, // 9: pb.RenameReq.request:type_name -> pb.NetRequest
	11, // 10: pb.RenameRsp.packet:type_name -> pb.NetPacket
	13, // 11: pb.RenameRsp.response:type_name -> pb.NetResponse
	11, // 12: pb.PrivateChatReq.packet:type_name -> pb.NetPacket
	12, // 13: pb.PrivateChatReq.request:type_name -> pb.NetRequest
	11, // 14: pb.PrivateChatRsp.packet:type_name -> pb.NetPacket
	13, // 15: pb.PrivateChatRsp.response:type_name -> pb.NetResponse
	11, // 16: pb.KickPush.packet:type_name -> pb.NetPacket
	14, // 17: pb.KickPush.push:type_name -> pb.NetPush
	11, // 18: pb.BroadcastPush.packet:type_name -> pb.NetPacket
	14, // 19: pb.BroadcastPush.push:type_name -> pb.NetPush
	11, // 20: pb.PrivateChatPush.packet:type_name -> pb.NetPacket
	14, // 21: pb.PrivateChatPush.push:type_name -> pb.NetPush
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_dao_proto_init() }
func file_dao_proto_init() {
	if File_dao_proto != nil {
		return
	}
	file_net_packet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dao_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateChatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateChatRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dao_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateChatPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dao_proto_goTypes,
		DependencyIndexes: file_dao_proto_depIdxs,
		MessageInfos:      file_dao_proto_msgTypes,
	}.Build()
	File_dao_proto = out.File
	file_dao_proto_rawDesc = nil
	file_dao_proto_goTypes = nil
	file_dao_proto_depIdxs = nil
}
