// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.4.0
// source: net-packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//协议类型
type ProtoType int32

const (
	ProtoType_PROTO_TYPE_UNKNOWN  ProtoType = 0
	ProtoType_PROTO_TYPE_REQUEST  ProtoType = 1
	ProtoType_PROTO_TYPE_RESPONSE ProtoType = 2
	ProtoType_PROTO_TYPE_PUSH     ProtoType = 3
)

// Enum value maps for ProtoType.
var (
	ProtoType_name = map[int32]string{
		0: "PROTO_TYPE_UNKNOWN",
		1: "PROTO_TYPE_REQUEST",
		2: "PROTO_TYPE_RESPONSE",
		3: "PROTO_TYPE_PUSH",
	}
	ProtoType_value = map[string]int32{
		"PROTO_TYPE_UNKNOWN":  0,
		"PROTO_TYPE_REQUEST":  1,
		"PROTO_TYPE_RESPONSE": 2,
		"PROTO_TYPE_PUSH":     3,
	}
)

func (x ProtoType) Enum() *ProtoType {
	p := new(ProtoType)
	*p = x
	return p
}

func (x ProtoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoType) Descriptor() protoreflect.EnumDescriptor {
	return file_net_packet_proto_enumTypes[0].Descriptor()
}

func (ProtoType) Type() protoreflect.EnumType {
	return &file_net_packet_proto_enumTypes[0]
}

func (x ProtoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoType.Descriptor instead.
func (ProtoType) EnumDescriptor() ([]byte, []int) {
	return file_net_packet_proto_rawDescGZIP(), []int{0}
}

type HeadPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtoType ProtoType `protobuf:"varint,1,opt,name=proto_type,json=protoType,proto3,enum=pb.ProtoType" json:"proto_type,omitempty"`
	Pid       uint32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"` //消息唯一id(请求、响应才会有)
	Type      uint32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Code      uint32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *HeadPack) Reset() {
	*x = HeadPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeadPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadPack) ProtoMessage() {}

func (x *HeadPack) ProtoReflect() protoreflect.Message {
	mi := &file_net_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadPack.ProtoReflect.Descriptor instead.
func (*HeadPack) Descriptor() ([]byte, []int) {
	return file_net_packet_proto_rawDescGZIP(), []int{0}
}

func (x *HeadPack) GetProtoType() ProtoType {
	if x != nil {
		return x.ProtoType
	}
	return ProtoType_PROTO_TYPE_UNKNOWN
}

func (x *HeadPack) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *HeadPack) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *HeadPack) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_net_packet_proto protoreflect.FileDescriptor

var file_net_packet_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x65, 0x74, 0x2d, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x72, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x64, 0x50, 0x61,
	0x63, 0x6b, 0x12, 0x2c, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x69, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x02,
	0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50,
	0x55, 0x53, 0x48, 0x10, 0x03, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6d, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_net_packet_proto_rawDescOnce sync.Once
	file_net_packet_proto_rawDescData = file_net_packet_proto_rawDesc
)

func file_net_packet_proto_rawDescGZIP() []byte {
	file_net_packet_proto_rawDescOnce.Do(func() {
		file_net_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_net_packet_proto_rawDescData)
	})
	return file_net_packet_proto_rawDescData
}

var file_net_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_net_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_net_packet_proto_goTypes = []interface{}{
	(ProtoType)(0),   // 0: pb.ProtoType
	(*HeadPack)(nil), // 1: pb.HeadPack
}
var file_net_packet_proto_depIdxs = []int32{
	0, // 0: pb.HeadPack.proto_type:type_name -> pb.ProtoType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_net_packet_proto_init() }
func file_net_packet_proto_init() {
	if File_net_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_net_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeadPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_net_packet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_packet_proto_goTypes,
		DependencyIndexes: file_net_packet_proto_depIdxs,
		EnumInfos:         file_net_packet_proto_enumTypes,
		MessageInfos:      file_net_packet_proto_msgTypes,
	}.Build()
	File_net_packet_proto = out.File
	file_net_packet_proto_rawDesc = nil
	file_net_packet_proto_goTypes = nil
	file_net_packet_proto_depIdxs = nil
}
